In [1]:
##importing pandas

import pandas as pd

In [11]:
##building my df 
data = pd.read_csv("copper-customs-value_annualized.csv")

In [12]:
##is this as ugly as i think it is ?
data.shape

(8, 1)

In [13]:
##answer yes, lets clean this mofo 
data=data.reset_index()

In [17]:
## transposing the data 
np_array = data.to_numpy().T
data = pd.DataFrame(np_array, index=data.columns, columns=data.index)

In [24]:
## resetting the column heads and cleaning the index 
data.columns = data.iloc[0]

In [25]:
data

,740620 Copper Powders Of Lamellar Structure; Flakes,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,6356569
0,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,6356569
1,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,6888106
2,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,25599543
3,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,43607323
4,7407103000 Profiles Of Refined Copper Not Holl...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,83717101
...,...,...,...,...,...,...,...,...
159,7419803000 Artcls O Cppr Nesoi Ctd Or Pltd W P...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,8285994
160,7419805010 Brass Plumbing Goods Nesoi (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,119085917
161,7419805010 Brass Plumbing Goods Nesoi (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,67413853
162,"7419805050 Other Articles Of Copper, Nesoi (kg)",World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,242265156
163,"7419805050 Other Articles Of Copper, Nesoi (kg)",World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,136914861

In [ ]:

# resetting the index and cleaning 
data = data.drop(data.index[0])

data = data.reset_index(drop=True)

In [23]:
data.head(10)

,740610 Copper Powders Of Non-lamellar Structure,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,35824819
0,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,6356569
1,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,6888106
2,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,25599543
3,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,43607323
4,7407103000 Profiles Of Refined Copper Not Holl...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,83717101
5,7407103000 Profiles Of Refined Copper Not Holl...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,35378811
6,7407105010 Bars A Rds Ref Cppr Hvg A Rctnglr C...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,294080661
7,7407105010 Bars A Rds Ref Cppr Hvg A Rctnglr C...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,68476335
8,7407105050 Bars And Rods Nesoi Of Refined Copp...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,182735520
9,7407105050 Bars And Rods Nesoi Of Refined Copp...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,160911621

In [9]:
copper[['HTS Code', 'Product Name']] = copper['Commodity'].str.split(' ',n=1, expand=True)

In [10]:
copper.to_csv("export-copper-customs_value-monthly.csv", index=False)